mongodb:
  image: mongo:latest

memcached:
  image: memcached:latest

app:
  build: .
  ports:
    - "80:3000"
  links:
    - mongodb
    - memcached
  environment:
    - RACK_ENV=production
    - MEMCACHE_SERVERS=memcached:11211
    - TWITTER_KEY
    - TWITTER_SECRET
