production:
  clients:
    default:
      database: rpaproxy
      hosts:
        - mongodb:27017
development:
  clients:
    default:
      database: rpaproxy-dev
      hosts:
        - mongodb:27017
test:
  clients:
    default:
      database: rpaproxy-test
      hosts:
        - mongodb:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
