production:
  sessions:
    default:
      database: rpaproxy
      hosts:
        - <%= ENV['MONGODB_PORT_27017_TCP_ADDR'] %>:<%= ENV['MONGODB_PORT_27017_TCP_PORT'] %>
development:
  sessions:
    default:
      database: rpaproxy-dev
      hosts:
        - <%= ENV['MONGODB_PORT_27017_TCP_ADDR'] %>:<%= ENV['MONGODB_PORT_27017_TCP_PORT'] %>
test:
  sessions:
    default:
      database: rpaproxy-test
      hosts:
        - <%= ENV['MONGODB_PORT_27017_TCP_ADDR'] %>:<%= ENV['MONGODB_PORT_27017_TCP_PORT'] %>
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
